{% set name = "pyexcel-xls" %}
{% set version = "0.5.9" %}
{% set sha256 = "d56cadea0a660684456976d98052554d3bbe2a78afc5f9a91c8691f626608555" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - pip
    - python
    - setuptools

  run:
    - python
    - pyexcel-io >=0.5.0
    - xlrd
    - xlwt

test:
  imports:
    - pyexcel_xls

about:
  home: https://github.com/pyexcel/pyexcel-xls
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A wrapper library to read, manipulate and write data in xls using xlrd and xlwt
  description: |
    'A wrapper library to read, manipulate and write data in xls format. It' +
    ' reads xlsx and xlsm format' +
    ''
  dev_url: https://github.com/pyexcel/pyexcel-xls

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
