travis:
  secure:
    BINSTAR_TOKEN: aL/gZc2XAn4WRMSbM/qHp+x/Gi50TsUe++Bh8ae4zOW0UEbNgZsXW6gfF1L4IxgqErXXAGYLL8u9UDSEF0HKdyQ4GMthkx0UHgaaa7PfBJubuR0EH4SlA1+FfLy2BiXH9d+sApjzi++BehVij2wL4qOUmeX0AMZzb/GTjpFjDEk36nrAyTdtBgpcIK+SZuIJXN7zV51v7pnHseV+sA8tu0FjXrWmJ8qFK2cZJlVmsymu+D1qOBAyVDGuMmA/zpaMkfIcaVrDuYWB97FgFhQ+kXxFtA47ffhczS1e0oSzAOHQOOwI1uiORih372A5g2D0Qz7Wn14rU5IAiDIX6ut324o4mn7ZvIRVr0QgYMUF0/goXTL4ZMQ9PSW6FWVk7vz+7BIGpTOwm0eT6LSN83k7fHat5O6YDjKvVjFzd4pFjKZjtg5LRqXwL92134sHYAycg03a/RJBTmI5lHb7DoZ5UePieQ+z9ajcXrQ+/baG1x31TWoFkSbsrAJsFKx2qNL6FLqYUHpwQAWG5zMYaZuyZrb9vPb6Sh+QgJ2/xWV70UMR3Niv082rFI+p+aC+v7L5Rz8DsC4Vi4Hzi1iPjh7sPl6l2eIWX8KXCataoFDPOSxi4PNRd9jPH/p9IugIUu/BUsvCMWA4V26fo0i6ilNtE1/urol8b+2r+zLm521HcDY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
