travis:
  secure:
    BINSTAR_TOKEN: pQnNhEdsRvCXjslpP6hERjzPgbu5pTiBZlcaD/+mgBbsiGVzc/91Dm2dUpdLv2JBL7oKIfJzxyc/fIw66iepzymj/+/Y9frW/Acr1GqdGYoOQBz9k/IgHJiPHUKAU6lg5rvHyM6PT2Qh+9v6075vsElULik9C14uVtEVHlcUReeOV+lmZAEpeaf5Os2G0G7Y1d21Oy2ebgoBZxQtysM0vVj5HD167eDIjJvZOwoYy+WSz5OTtG90A6CK1yjGbf03R4yyEhzBLcADOmdAo6n+Ki0NYpUvhWCA4ztTBxFjsHTVZrs/BXgpD9EHLgsKwCA7DuVNMhavK5Js0lbA11cJ2VrdvXoF9jrm7XKYLyxbIvVgXtqW1jLSNesVgBrlljsLKKnIhg/sRGUKrRM/rtiOzUP0aCpnrHUVl26WW2H01nscfdBvHia3rwOQDF7N4XObJR4FLOlFRd+RKwQV4G8Vt8NZm1aW2Xyx3KckBB0Joe9yhxdFZchcXAzyj/jcaxHsVEYIzpaAWHOBhbbcTOgeI2H6XZBiiyzBme1MWhaNEpsw6ww7Be3oStL3T8BfCU15qmhC3Tbf6c9TA/E0LXOr9vGTksPaI1gf0tbHP5U287GZ9c1F5Tc5JKzyLUM8Q4HDDdWNkfsK0XiwV+B4muZq+zTDg9sz4K8C/9JiKph4QuU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
